#---
#- name: Setup vm
#  hosts: all
#
#  tasks:
  
  - name: print operating system
    ansible.builtin.debug:
      var: ansible_facts['distribution']

  - name: Update packages Debian
    become: true
    raw: apt-get update
    when: ansible_facts['os_family'] == "Debian"

  - name: Install ufw
    apt:
      name: ufw
      state: present
    when: ansible_facts['os_family'] == "Debian"


  - name: Disable firewall for centos
    become: true
    ansible.builtin.service:
      name: firewalld
      enabled: false
    when: ansible_facts['distribution'] == "CentOS"

  - name: Register firewall for ubuntu
    ufw:
      state: disabled
    when: ansible_facts['distribution'] == "Ubuntu"


  - name: Install SELinux-policy for RedHat
    become: true
    yum:
      name: selinux-policy-doc.noarch
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Put SELinux in permissive mode centos
    selinux:
      #policy: targeted
      state: disabled
    when: ansible_facts['distribution'] == "CentOS"

  - name: Rebbot for change to take affect RedHat
    become: true
    ansible.builtin.service:
      name: selinux
      enabled: restarted
    when: ansible_facts['distribution'] == "RedHat"

  - name: Disable swap Ubuntu
    raw: swapoff -a; sed -i '/swap/d' /etc/fstab
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Disable SWAP RedHat 1/2
    raw: swapoff -a
    when: ansible_facts['os_family'] == "NotDefined"

  - name: Disable SWAP RedHat 2/2
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
    when: ansible_facts['os_family'] == "NotDefined"


  - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

  - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

      
  - name: Add the iptables rule to sysctl.conf
    raw: echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf
  
  - name: Safe settings
    raw: sysctl --system