---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: instance
    image: ami-05f7491af5eef733a
    instance_type: t2.micro
    vpc_subnet_id: subnet-03f0483cabb6ef976
provisioner:
  name: ansible
verifier:
  name: ansible
