   
---
name: Molecule Test
on: [push, pull_request]
jobs:
  Test_Molecule:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Print ansible version
        run: ansible --version

      - name: Install test dependencies
        run: pip3 install molecule[docker] && pip3 install "ansible-lint[core,yamllint]" && python3 -m pip install --upgrade pip && molecule init role -d ec2 my-role
        
      - name: Install ansible modules
        run: ansible-galaxy collection install community.general && ansible-galaxy collection install ansible.posix
        
      - name: Molecule test
        run: |
          molecule test
