   
---
name: Molecule Test
on: [push, pull_request]
jobs:
  Test_Molecule:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Print ansible version
        run: ansible --version

      - name: Install test dependencies
        run: pip3 install molecule[ec2] && pip3 install "ansible-lint[core,yamllint]" && python3 -m pip install --upgrade pip &&  pip install molecule-ec2 && pip install botocore && pip install boto3 && pip install boto
                
      - name: Set credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-region: eu-central-1
         aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
         aws-secret-access-key: ${{ secrets.AWSACCESSKEY }}
          
      - name: Install ansible modules
        run: ansible-galaxy collection install community.general && ansible-galaxy collection install ansible.posix && ansible-galaxy collection install amazon.aws
        
      - name: Molecule test
        run: |
          molecule test
